### ISSUE TITLE
ASCII easter egg is broken

### ISSUE THREAD

**Issue by zamiang** [artsy/force-public#11]
Looks like the API request goes to fusion.artsy.net which returns an empty object for the .txt api request. The client then gets that and appends `[object Object] below the artwork.
![screenshot 2016-01-11 12 12 53](https://cloud.githubusercontent.com/assets/110563/12240684/db125f70-b85c-11e5-82f7-47f779f1c87a.png)

**Comment by zamiang** [comment]
@craigspaeth

**Comment by orta** [comment]
@mzikherman - did the new image pipeline stuff end up removing the ASCII-fy-ness?

**Comment by mzikherman** [comment]
Yes, we don't really support that anymore :(

**Comment by orta** [comment]
OK, calling the feature dead - if you care @zamiang - it's still alive in iOS where we do the conversion natively
