### ISSUE TITLE
feature request: follow / unfollow on artist page

### ISSUE THREAD

**Issue by svnlto** [artsy/force-public#13]
Not sure how open you are towards feature requests, but I personally think, putting a link on the artist view page would be a significant UX improvement. 

-

Follow Artist:
![screen shot 2016-02-01 at 21 58 39](https://cloud.githubusercontent.com/assets/103989/12731107/6d40aa54-c92f-11e5-862e-d958e447c006.png)

Following Artist:

![screen shot 2016-02-01 at 21 57 18](https://cloud.githubusercontent.com/assets/103989/12731116/7954d770-c92f-11e5-94a2-1b520926dd50.png)

Unfollow Artist:

![screen shot 2016-02-01 at 22 03 57](https://cloud.githubusercontent.com/assets/103989/12731193/f162aed6-c92f-11e5-9db5-02741d99669a.png)

**Comment by orta** [comment]
This happened with the new Artist design pages for the web!

![screen shot 2016-04-04 at 09 57 29](https://cloud.githubusercontent.com/assets/49038/14243135/b330a580-fa4b-11e5-846a-9cb10a587583.png)
