### ISSUE TITLE
 Env file and Gravity Link 

### ISSUE THREAD

**Issue by Branca** [artsy/force-public#14]
hello please I would love to run the force on localhost , but what should I put in .env file? and how to use gravity to the offered link is broken ?

thanksQ
Branca

**Comment by orta** [comment]
Hey @Branca  - I've pushed some code on the internal repo that eventually becomes the OSS one in  order to address this issue. 

However, in the mean-time. Your `.env` file should look like this:

``` sh
	SESSION_SECRET=oss-session
	SESSION_COOKIE_KEY=force.sess
	ARTSY_ID=e750db60ac506978fc70
	ARTSY_SECRET=3a33d2085cbd1176153f99781bbce7c6
	FACEBOOK_ID=72348234632423423
	FACEBOOK_SECRET=234234234234
	TWITTER_KEY=234234234
	TWITTER_SECRET=43242342342
	EMBEDLY_KEY=3242534543564577
	IMAGES_URL_PREFIX=http://static%d.artsy.net
	MIXPANEL_ID=3254235436564
	EMPTY_COLLECTION_SET_ID=51ba3bcc0abd8521b300002f
	GEMINI_S3_ACCESS_KEY=1432423423
	GOOGLE_SEARCH_KEY=242342weerwerwe
	GOOGLE_SEARCH_CX=werwerwe32525-chum
	SEGMENT_WRITE_KEY=sdfsdfertwt
	S3_KEY=34234sdfsdfds32423
	S3_SECRET=ewfsdjbgbk2342dsafghu
	POSITRON_URL=http://writer.artsy.net
	MAILCHIMP_KEY=asdasd2123123
	GALLERY_INSIGHTS_LIST=12312weasdas
	NODE_ENV=development
	METAPHYSICS_ENDPOINT=http://metaphysics-staging.artsy.net
	STRIPE_PUBLISHABLE_KEY=asdffcvxcv3342342
	SAILTHRU_KEY=erweasdasd3423525hhg
	SAILTHRU_SECRET=fmsdfbsdfmb3324234
```
WRT Gravity, that's totally behind closed doors, I'm afraid we don't have plans around making this available for introspection ATM - I'll improve the wording there too.

**Comment by Branca** [comment]
very grateful for the answer? but what name the file should have .env ? and
where it should stay within the DORCE -public folder? What can I use
instead of gravity to be able to run locally force ?

2016-04-04 5:22 GMT-03:00 Orta <notifications@github.com>:

> Closed #14 <https://github.com/artsy/force-public/issues/14>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/force-public/issues/14#event-613237091>
>



-- 
Branca! - Brancalion Desenhos para todas as mídias!!! São Paulo - Brasil
www.brancalion.com.br

**Comment by orta** [comment]
The file name is `.env` and it sits inside the root of the `force-public` folder ( so it should be `force-public/.env) - you can then run `make ss` to run against our gravity servers instead of your own version.

**Comment by Branca** [comment]
'm almost there!

what 's wrong here after running make ss ?

APP_URL = http : // localhost: 5000 APPLICATION_NAME = force -staging
API_URL = https : //stagingapi.artsy.net foreman start
08:02:17 web.1 | started with pid 3644
08:02:17 web.1 | node_modules / .bin / forever node_modules / .bin /
coffee --nodejs --max_old_space_size = 960 index.coffee
08:02:17 web.1 | make [ 1 ] : node_modules / .bin / forever : No such
file or directory
08:02:17 web.1 | make [ 1 ] : *** [ sf ] Error 1
08:02:17 web.1 | exited with code 2
8:02:17 system | sending SIGTERM to all processes


2016-04-04 7:55 GMT-03:00 Orta <notifications@github.com>:

> The file name is .env and it sits inside the root of the force-public
> folder ( so it should be force-public/.env) - you can then runmake ss` to
> run against our gravity servers instead of your own version.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/artsy/force-public/issues/14#issuecomment-205240495>
>



-- 
Branca! - Brancalion Desenhos para todas as mídias!!! São Paulo - Brasil
www.brancalion.com.br

**Comment by Branca** [comment]
this missing install npm bin ? what better way to do this ?

2016-04-04 8:03 GMT-03:00 Mauricio Brancalion <mauricio.brancalion@gmail.com
>:

> 'm almost there!
>
> what 's wrong here after running make ss ?
>
> APP_URL = http : // localhost: 5000 APPLICATION_NAME = force -staging API_URL = https : //stagingapi.artsy.net foreman start
> 08:02:17 web.1 | started with pid 3644
> 08:02:17 web.1 | node_modules / .bin / forever node_modules / .bin / coffee --nodejs --max_old_space_size = 960 index.coffee
> 08:02:17 web.1 | make [ 1 ] : node_modules / .bin / forever : No such file or directory
> 08:02:17 web.1 | make [ 1 ] : *** [ sf ] Error 1
> 08:02:17 web.1 | exited with code 2
> 8:02:17 system | sending SIGTERM to all processes
>
>
> 2016-04-04 7:55 GMT-03:00 Orta <notifications@github.com>:
>
>> The file name is .env and it sits inside the root of the force-public
>> folder ( so it should be force-public/.env) - you can then runmake ss`
>> to run against our gravity servers instead of your own version.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/artsy/force-public/issues/14#issuecomment-205240495>
>>
>
>
>
> --
> Branca! - Brancalion Desenhos para todas as mídias!!! São Paulo - Brasil
> www.brancalion.com.br
>



-- 
Branca! - Brancalion Desenhos para todas as mídias!!! São Paulo - Brasil
www.brancalion.com.br
