### ISSUE TITLE
Artworks in fillwidth-style row on article display extremely large

### ISSUE THREAD

**Issue by zamiang** [artsy/force-public#9]
@craigspaeth - Quick Friday night bug report…  ¯\\\_(°\_o)\_/¯

On prod I see: 
<img width="1438" alt="screenshot 2015-08-07 23 23 39" src="https://cloud.githubusercontent.com/assets/110563/9148865/5f1bdc06-3d5b-11e5-8392-c2c942cec1b0.png">
https://www.artsy.net/article/artsy-editorial-6-couples-who-are-shaping-contemporary-design
(verified in Safari as well)

There are certainly more complex things going on here…but in dev tools land, I could fix the problem by doing 2 things:
- add 'max-width: 100%;' to the `figure` element
- remove the inline height attribute on `artwork-item-image-container`

Look I fixededed it:
<img width="1264" alt="screenshot 2015-08-07 23 20 29" src="https://cloud.githubusercontent.com/assets/110563/9148857/1edc9f90-3d5b-11e5-9ad9-726d93e9e975.png">

**Comment by craigspaeth** [comment]
Amazing! Thanks for the bug report @zamiang!

**Comment by orta** [comment]
This is fixed - closing!
